//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Datum&quot;,&quot;Naam / Omschrijving&quot;,&quot;Rekening&quot;,&quot;Tegenrekening&quot;,&quot;Code&quot;,&quot;Af Bij&quot;,&quot;Bedrag (EUR)&quot;,&quot;MutatieSoort&quot;,&quot;Mededelingen&quot;
        ///&quot;05-11-2014&quot;,&quot;Jumbo 233062 TILBURG NLD&quot;,&quot;NL59 INGB 0758 1114 79&quot;,&quot;&quot;,&quot;BA&quot;,&quot;Af&quot;,&quot;6,11&quot;,&quot;Betaalautomaat&quot;,&quot; Pasvolgnr:003 04-11-2014 15:47 Transactie:972779 Term:4VQK01&quot;
        ///&quot;05-11-2014&quot;,&quot;Albron Nederland BV DE MEERN NLD&quot;,&quot;NL59 INGB 0758 1114 79&quot;,&quot;&quot;,&quot;BA&quot;,&quot;Af&quot;,&quot;2,25&quot;,&quot;Betaalautomaat&quot;,&quot; Pasvolgnr:003 04-11-2014 12:33 Transactie:89O4Q0 Term:6L3MLW&quot;
        ///&quot;03-11-2014&quot;,&quot;094 Aldi TILBURG NLD&quot;,&quot;NL59 INGB 0758 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
    }
}
